### ISSUE TITLE
Some nasty error has occurred, please try again  Error: Unable to upload the photo: Error: Try another photo

### ISSUE THREAD

**Issue by Yuri-Neko** [lmcsu/qq-neural-anime-tg#7]
Invalid request {"code":-2100,"msg":"the busi_id: <ai_painting_spring_entry> is not servered in this set group"}
QQ file upload error caught: Error: Try another photo.
Error has occurred for 5612165840
Error: Unable to upload the photo: Error: Try another photo.
    at request (/home/runner/qq-neural-anime-tg/index.ts:234:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async qqRequest (/home/runner/qq-neural-anime-tg/index.ts:253:26)
    at async onPhotoReceived (/home/runner/qq-neural-anime-tg/index.ts:532:23)
Users: 0 | Requests: 0

**Comment by lmcsu** [comment]
Take a look at exactly the previous issue #6
